name: "Missing Lyrics"
description: "Lyrics that are Missing for a Song."
title: "First Songs' Name // Artists"
labels: ["Missing Lyrics"]
assignees: surfbryce

body:
  - type: checkboxes
    id: "pre-checklist"
    attributes:
      label: "Before you list your Songs:"
      options:
        - label: "IF you are reporting multiple songs, add \", ...\" to the end of your title."
          required: true
        - label: "For every song you want to report, check Musixmatch or Apple Music and check to see if they even have Lyrics for the Songs you are reporting."
          required: true
  - type: textarea
    id: "song-links"
    attributes:
      label: "List Song Links"
      description: "For each song, copy its link, and then list each one numerically."
      placeholder: |
        1. https://open.spotify.com/track/1FkNQCYnaSvTPqXjpsB13X
        2. https://open.spotify.com/track/4xjjaT7yDpZ6jDRZXBHxM4
        3. https://open.spotify.com/track/2YcPBBa0K32C429HT77RT0
        4. https://open.spotify.com/track/5lcgNTL58YoaD2W5O3hb3V?si=b102aea295d94823
